__author__ = """Wenyu Ouyang"""
__email__ = "wenyuouyang@outlook.com"
# Import version from _version.py (auto-generated by hatch-vcs)
try:
    from ._version import __version__, __version_tuple__
except ImportError:
    # Fallback version if _version.py doesn't exist yet
    __version__ = "0.0.0+unknown"
    __version_tuple__ = (0, 0, 0, "unknown")
